import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home () {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        SVG LOGO ON HERE
      </header>

      <main className={styles.main}>

        <nav className={styles.nav}>
          <ul className={styles.ul}>
            <li className={styles.li}>nunca mais</li>
            <li className={styles.li}>esqueça</li>
            <li className={styles.li}>os aniversários</li>
          </ul>
        </nav>

        <div className={styles.box_buttons}>
          <Link href='/login'>
            <button>Entrar</button>
          </Link>
          <Link href='/register'>
            <button>Registrar</button>
          </Link>
        </div>

      </main>

      <footer className={styles.footer}>
        Feito com 🤍 por devAlexSilva👨🏾‍💻
      </footer>
    </div>
  )
}
